---
type: showroom

# Set the left column width to 30%
default_width: 30
# Persist the URL state so browser refresh doesn't reset the UI
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: Webmail
    url: "https://test-email-server-ui-user-${GUID}-it-selfsvc.${DOMAIN}"
